-- AlterTable
ALTER TABLE `report` ADD COLUMN `isPublished` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `publishAt` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('PUBLIC', 'PRIVATE', 'DRAFT', 'PUBLISHED', 'IN_REVIEW') NULL DEFAULT 'PUBLIC';
